"""change unittype of purchase unit

Revision ID: 0a2e01a41d72
Revises: 2d347ad8836b
Create Date: 2026-02-01 11:22:11.484711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a2e01a41d72'
down_revision: Union[str, Sequence[str], None] = '2d347ad8836b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'purchase_unit',
               existing_type=postgresql.ENUM('kg', 'gm', 'mg', 'liter', 'ml', name='unittype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'purchase_unit',
               existing_type=postgresql.ENUM('kg', 'gm', 'mg', 'liter', 'ml', name='unittype'),
               nullable=False)
    # ### end Alembic commands ###
