"""added boolean field

Revision ID: 0b2ab3ebe20d
Revises: 944a1694eaaf
Create Date: 2026-04-06 09:00:11.720648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2ab3ebe20d'
down_revision: Union[str, Sequence[str], None] = '944a1694eaaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('is_fixed_cost', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'is_fixed_cost')
    # ### end Alembic commands ###
