"""add for_ex and forxcfd to user_branch_access

Revision ID: 10878ac3dd3d
Revises: 3d4efe29f074
Create Date: 2026-01-04 19:21:26.331436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10878ac3dd3d'
down_revision: Union[str, Sequence[str], None] = '3d4efe29f074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_branch_access', sa.Column('for_ex', sa.Boolean(), nullable=True))
    op.add_column('user_branch_access', sa.Column('forxcfd', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_branch_access', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('user_branch_access', 'forxcfd')
    op.drop_column('user_branch_access', 'for_ex')
    op.alter_column('tenants', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('storage_locations', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('pre_preparedmaterial', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('item_categories', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('inventory_batches', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('inventory', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
