"""added mobile_no field

Revision ID: 19b2a249acf6
Revises: 7527911f1c3d
Create Date: 2026-01-05 14:30:07.952624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b2a249acf6'
down_revision: Union[str, Sequence[str], None] = '7527911f1c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mobile_no', sa.String(length=15), nullable=False))
    op.create_index(op.f('ix_users_mobile_no'), 'users', ['mobile_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_mobile_no'), table_name='users')
    op.drop_column('users', 'mobile_no')
    # ### end Alembic commands ###
