"""increase numeric value size in wastage model

Revision ID: 24355048d909
Revises: 35687e7604c4
Create Date: 2026-05-15 11:43:12.288373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24355048d909'
down_revision: Union[str, Sequence[str], None] = '35687e7604c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wastage_management', 'cost_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wastage_management', 'cost_value',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
