"""added unit field in inventory transactions table

Revision ID: 24f1e1fd637a
Revises: f1a1e4cc091e
Create Date: 2026-03-23 11:46:21.056671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f1e1fd637a'
down_revision: Union[str, Sequence[str], None] = 'f1a1e4cc091e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_transactions', sa.Column('unit', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_transactions', 'unit')
    # ### end Alembic commands ###
