"""add two fields in inventory transaction table

Revision ID: 2c5ea60fb348
Revises: 838dae52695d
Create Date: 2026-01-25 18:32:11.785774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c5ea60fb348'
down_revision: Union[str, Sequence[str], None] = '838dae52695d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_transactions', sa.Column('dish_ingredient_id', sa.Integer(), nullable=True))
    op.add_column('inventory_transactions', sa.Column('pre_prepared_material_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'inventory_transactions', 'dish_ingredients', ['dish_ingredient_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'inventory_transactions', 'pre_prepared_dish_preparation', ['pre_prepared_material_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_constraint(None, 'inventory_transactions', type_='foreignkey')
    op.drop_column('inventory_transactions', 'pre_prepared_material_id')
    op.drop_column('inventory_transactions', 'dish_ingredient_id')
    # ### end Alembic commands ###
