"""added waste management table

Revision ID: 2ce154bf949e
Revises: b2b36c0017b3
Create Date: 2026-02-23 09:36:49.688944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ce154bf949e'
down_revision: Union[str, Sequence[str], None] = 'b2b36c0017b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wastage_management', sa.Column('semi_finished_product_id', sa.UUID(), nullable=True))
    op.add_column('wastage_management', sa.Column('semi_finished_batch_id', sa.Integer(), nullable=True))
    op.add_column('wastage_management', sa.Column('preparation_log_id', sa.Integer(), nullable=True))
    op.add_column('wastage_management', sa.Column('unit', sa.String(length=50), nullable=True))
    op.add_column('wastage_management', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('wastage_management', sa.Column('is_breakdown', sa.Boolean(), nullable=True))
    op.add_column('wastage_management', sa.Column('parent_wastage_id', sa.UUID(), nullable=True))
    op.alter_column('wastage_management', 'wastage_type',
               existing_type=postgresql.ENUM('DISH', 'INVENTORY', name='wastagetype'),
               nullable=False)
    op.alter_column('wastage_management', 'quantity_wasted',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.alter_column('wastage_management', 'wastage_reason',
               existing_type=postgresql.ENUM('EXPIRY', 'DAMAGE', 'CONTAMINATION', 'UNSOLD_DISH', 'PREPARATION_ERROR', 'SPILLAGE', 'STAFF_MEAL', 'SAMPLING', 'OTHER', name='wastagereason'),
               nullable=False)
    op.alter_column('wastage_management', 'wastage_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'wastage_management', 'pre_prepared_dish_preparation', ['semi_finished_product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'wastage_management', 'wastage_management', ['parent_wastage_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'wastage_management', 'dish_preparation_batch_logs', ['preparation_log_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'wastage_management', 'pre_prepared_material_stock', ['semi_finished_batch_id'], ['id'], ondelete='SET NULL')
    op.execute("ALTER TYPE wastagetype ADD VALUE 'semi_finished'")
    op.execute("ALTER TYPE wastagetype ADD VALUE IF NOT EXISTS 'semi_finished'")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wastage_management', type_='foreignkey')
    op.drop_constraint(None, 'wastage_management', type_='foreignkey')
    op.drop_constraint(None, 'wastage_management', type_='foreignkey')
    op.drop_constraint(None, 'wastage_management', type_='foreignkey')
    op.alter_column('wastage_management', 'wastage_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('wastage_management', 'wastage_reason',
               existing_type=postgresql.ENUM('EXPIRY', 'DAMAGE', 'CONTAMINATION', 'UNSOLD_DISH', 'PREPARATION_ERROR', 'SPILLAGE', 'STAFF_MEAL', 'SAMPLING', 'OTHER', name='wastagereason'),
               nullable=True)
    op.alter_column('wastage_management', 'quantity_wasted',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.alter_column('wastage_management', 'wastage_type',
               existing_type=postgresql.ENUM('DISH', 'INVENTORY', name='wastagetype'),
               nullable=True)
    op.drop_column('wastage_management', 'parent_wastage_id')
    op.drop_column('wastage_management', 'is_breakdown')
    op.drop_column('wastage_management', 'notes')
    op.drop_column('wastage_management', 'unit')
    op.drop_column('wastage_management', 'preparation_log_id')
    op.drop_column('wastage_management', 'semi_finished_batch_id')
    op.drop_column('wastage_management', 'semi_finished_product_id')
    # ### end Alembic commands ###
