"""add combo table

Revision ID: 3b060e8d7743
Revises: 24355048d909
Create Date: 2026-05-21 07:01:11.838304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b060e8d7743'
down_revision: Union[str, Sequence[str], None] = '24355048d909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('computed_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['dish_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combos_id'), 'combos', ['id'], unique=False)
    op.create_index(op.f('ix_combos_name'), 'combos', ['name'], unique=False)
    op.create_index(op.f('ix_combos_tenant_id'), 'combos', ['tenant_id'], unique=False)
    op.create_table('combo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('combo_id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.Column('semi_finished_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.Column('fixed_cost_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('\n            (\n                (dish_id IS NOT NULL)::int +\n                (semi_finished_id IS NOT NULL)::int +\n                (ingredient_id IS NOT NULL)::int\n            ) = 1\n            ', name='ck_combo_item_single_source'),
    sa.ForeignKeyConstraint(['combo_id'], ['combos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['inventory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semi_finished_id'], ['semi_finished_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combo_items_id'), 'combo_items', ['id'], unique=False)
    op.create_index(op.f('ix_combo_items_item_name'), 'combo_items', ['item_name'], unique=False)
    op.create_index(op.f('ix_combo_items_tenant_id'), 'combo_items', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_combo_items_tenant_id'), table_name='combo_items')
    op.drop_index(op.f('ix_combo_items_item_name'), table_name='combo_items')
    op.drop_index(op.f('ix_combo_items_id'), table_name='combo_items')
    op.drop_table('combo_items')
    op.drop_index(op.f('ix_combos_tenant_id'), table_name='combos')
    op.drop_index(op.f('ix_combos_name'), table_name='combos')
    op.drop_index(op.f('ix_combos_id'), table_name='combos')
    op.drop_table('combos')
    # ### end Alembic commands ###
