"""add perishable in inventory

Revision ID: 4383d20188dd
Revises: c7e20e276fb2
Create Date: 2026-02-07 15:11:27.020843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4383d20188dd'
down_revision: Union[str, Sequence[str], None] = 'c7e20e276fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert_configurations', 'alert_type',
               existing_type=postgresql.ENUM('LOW_STOCK', 'OUT_OF_STOCK', 'EXPIRY_WARNING', 'BATCH_TYPE', name='alerttype'),
               nullable=True)
    op.alter_column('expenses', 'item_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('expenses', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('expenses', 'total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('expenses', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('inventory', sa.Column('lifecycle_stage', sa.Enum('FRESH', 'NEAR_EXPIRY', 'EXPIRED', name='perishablelifecycle'), nullable=True))
    op.alter_column('inventory', 'item_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inventory', 'sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('inventory', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('inventory', 'unit',
               existing_type=postgresql.ENUM('kg', 'gm', 'mg', 'L', 'ml', 'liter', name='unittype'),
               nullable=True)
    op.alter_column('inventory', 'price_per_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('inventory', 'total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # FIXED: Added postgresql_using parameter to handle VARCHAR to ENUM conversion
    op.alter_column('inventory', 'purchase_unit',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('kg', 'gm', 'mg', 'liter', 'ml', name='unittype'),
               existing_nullable=True,
               postgresql_using='purchase_unit::unittype')
    op.alter_column('inventory', 'reorder_point',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.alter_column('inventory', 'date_added',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('inventory_alert', 'inventory_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory_alert', 'alert_type',
               existing_type=postgresql.ENUM('LOW_STOCK', 'OUT_OF_STOCK', 'EXPIRY_WARNING', 'BATCH_TYPE', name='alerttype'),
               nullable=True)
    op.alter_column('inventory_alert', 'message',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('inventory_batches', 'inventory_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory_batches', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory_batches', 'batch_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('inventory_batches', 'unit',
               existing_type=postgresql.ENUM('kg', 'gm', 'mg', 'L', 'ml', 'liter', name='unittype'),
               nullable=True)
    op.alter_column('inventory_transactions', 'inventory_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory_transactions', 'transaction_type',
               existing_type=postgresql.ENUM('PURCHASE', 'PREPARATION', 'SALE', 'ADJUSTMENT', 'WASTAGE', name='transactiontype'),
               nullable=True)
    op.alter_column('inventory_transactions', 'quantity',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.alter_column('item_categories', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('item_categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('item_categories', 'category_type',
               existing_type=postgresql.ENUM('perishable', 'non_perishable', name='item_category_type'),
               nullable=True)
    op.alter_column('pre_preparedmaterial', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pre_preparedmaterial', 'inventory_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pre_preparedmaterial', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('storage_locations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('storage_locations', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('tenants', 'tenant_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('user_branch_access', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_branch_access', 'branch_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'mobile_no',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'mobile_no',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user_branch_access', 'branch_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_branch_access', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tenants', 'tenant_name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('storage_locations', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('storage_locations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pre_preparedmaterial', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pre_preparedmaterial', 'inventory_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pre_preparedmaterial', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('item_categories', 'category_type',
               existing_type=postgresql.ENUM('perishable', 'non_perishable', name='item_category_type'),
               nullable=False)
    op.alter_column('item_categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('item_categories', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory_transactions', 'quantity',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.alter_column('inventory_transactions', 'transaction_type',
               existing_type=postgresql.ENUM('PURCHASE', 'PREPARATION', 'SALE', 'ADJUSTMENT', 'WASTAGE', name='transactiontype'),
               nullable=False)
    op.alter_column('inventory_transactions', 'inventory_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory_batches', 'unit',
               existing_type=postgresql.ENUM('kg', 'gm', 'mg', 'L', 'ml', 'liter', name='unittype'),
               nullable=False)
    op.alter_column('inventory_batches', 'batch_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('inventory_batches', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory_batches', 'inventory_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory_alert', 'message',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('inventory_alert', 'alert_type',
               existing_type=postgresql.ENUM('LOW_STOCK', 'OUT_OF_STOCK', 'EXPIRY_WARNING', 'BATCH_TYPE', name='alerttype'),
               nullable=False)
    op.alter_column('inventory_alert', 'inventory_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory', 'date_added',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('inventory', 'reorder_point',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    # FIXED: Added postgresql_using parameter for downgrade as well
    op.alter_column('inventory', 'purchase_unit',
               existing_type=sa.Enum('kg', 'gm', 'mg', 'liter', 'ml', name='unittype'),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='purchase_unit::text')
    op.alter_column('inventory', 'total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('inventory', 'price_per_unit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('inventory', 'unit',
               existing_type=postgresql.ENUM('kg', 'gm', 'mg', 'L', 'ml', 'liter', name='unittype'),
               nullable=False)
    op.alter_column('inventory', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('inventory', 'sku',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('inventory', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('inventory', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory', 'item_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('inventory', 'lifecycle_stage')
    op.alter_column('expenses', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('expenses', 'total_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('expenses', 'quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('expenses', 'item_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('alert_configurations', 'alert_type',
               existing_type=postgresql.ENUM('LOW_STOCK', 'OUT_OF_STOCK', 'EXPIRY_WARNING', 'BATCH_TYPE', name='alerttype'),
               nullable=False)
    