"""add cogs_amount field in dish sale

Revision ID: 4804545b1bcb
Revises: b9131175e5f0
Create Date: 2026-04-24 09:22:06.226741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4804545b1bcb'
down_revision: Union[str, Sequence[str], None] = 'b9131175e5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_sales', sa.Column('cogs_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish_sales', 'cogs_amount')
    # ### end Alembic commands ###
