"""added fixed_cost_amount in dish ingredient table

Revision ID: 485692ea86a7
Revises: 7a9965ace63c
Create Date: 2026-04-20 12:51:14.585875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '485692ea86a7'
down_revision: Union[str, Sequence[str], None] = '7a9965ace63c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_ingredients', sa.Column('fixed_cost_amount', sa.Float(), nullable=True))
    op.create_index(op.f('ix_dish_types_name'), 'dish_types', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dish_types_name'), table_name='dish_types')
    op.drop_column('dish_ingredients', 'fixed_cost_amount')
    # ### end Alembic commands ###
