"""added few fields

Revision ID: 4f5ba34a5a72
Revises: be2d7badcd85
Create Date: 2026-01-06 12:27:42.740263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f5ba34a5a72'
down_revision: Union[str, Sequence[str], None] = 'be2d7badcd85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('purchase_unit', sa.String(), nullable=False))
    op.add_column('inventory', sa.Column('purchase_unit_size', sa.Integer(), nullable=False))
    op.add_column('inventory_batches', sa.Column('packets', sa.Integer(), nullable=True))
    op.add_column('inventory_batches', sa.Column('pieces', sa.Integer(), nullable=True))
    op.add_column('inventory_batches', sa.Column('total_pieces', sa.Integer(), nullable=True))
    op.add_column('inventory_batches', sa.Column('price_per_packet', sa.Float(), nullable=True))
    op.add_column('inventory_batches', sa.Column('price_per_piece', sa.Float(), nullable=True))
    op.alter_column('inventory_batches', 'quantity_received',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.alter_column('inventory_batches', 'quantity_remaining',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_batches', 'quantity_remaining',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.alter_column('inventory_batches', 'quantity_received',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.drop_column('inventory_batches', 'price_per_piece')
    op.drop_column('inventory_batches', 'price_per_packet')
    op.drop_column('inventory_batches', 'total_pieces')
    op.drop_column('inventory_batches', 'pieces')
    op.drop_column('inventory_batches', 'packets')
    op.drop_column('inventory', 'purchase_unit_size')
    op.drop_column('inventory', 'purchase_unit')
    # ### end Alembic commands ###
