"""added user_id to item

Revision ID: 50b285ad9f13
Revises: 8928c8dca07d
Create Date: 2026-01-21 09:10:26.035640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50b285ad9f13'
down_revision: Union[str, Sequence[str], None] = '8928c8dca07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'inventory', 'users', ['user_id'], ['id'])
    op.add_column('inventory_batches', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'inventory_batches', 'users', ['user_id'], ['id'])
    op.add_column('item_categories', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'item_categories', 'users', ['user_id'], ['id'])
    op.add_column('pre_preparedmaterial', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pre_preparedmaterial', 'users', ['user_id'], ['id'])
    op.add_column('storage_locations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'storage_locations', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('super_admin', 'branch_manager', 'kitchen_manager', 'inventory_clerk', 'chef_cook', 'accountant', 'viewer', name='userrole'),
               type_=sa.Enum('super_admin', 'branch_manager', 'kitchen_manager', 'inventory_clerk', 'chef_cook', 'accountant', 'viewer', name='userrole', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('super_admin', 'branch_manager', 'kitchen_manager', 'inventory_clerk', 'chef_cook', 'accountant', 'viewer', name='userrole', native_enum=False),
               type_=postgresql.ENUM('super_admin', 'branch_manager', 'kitchen_manager', 'inventory_clerk', 'chef_cook', 'accountant', 'viewer', name='userrole'),
               existing_nullable=False)
    op.drop_constraint(None, 'storage_locations', type_='foreignkey')
    op.drop_column('storage_locations', 'user_id')
    op.drop_constraint(None, 'pre_preparedmaterial', type_='foreignkey')
    op.drop_column('pre_preparedmaterial', 'user_id')
    op.drop_constraint(None, 'item_categories', type_='foreignkey')
    op.drop_column('item_categories', 'user_id')
    op.drop_constraint(None, 'inventory_batches', type_='foreignkey')
    op.drop_column('inventory_batches', 'user_id')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_column('inventory', 'user_id')
    # ### end Alembic commands ###
