"""increase numeric value number

Revision ID: 550739543a26
Revises: 89e02c21b73f
Create Date: 2026-05-08 06:12:18.333531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550739543a26'
down_revision: Union[str, Sequence[str], None] = '89e02c21b73f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_batches', 'quantity_received',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=True)
    op.alter_column('inventory_batches', 'quantity_remaining',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               type_=sa.Numeric(precision=12, scale=4),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_batches', 'quantity_remaining',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=12, scale=3),
               existing_nullable=True)
    op.alter_column('inventory_batches', 'quantity_received',
               existing_type=sa.Numeric(precision=12, scale=4),
               type_=sa.NUMERIC(precision=12, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###
