"""added is_semi_finished field

Revision ID: 5ba7d291ffe5
Revises: 550739543a26
Create Date: 2026-05-08 10:17:04.688767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba7d291ffe5'
down_revision: Union[str, Sequence[str], None] = '550739543a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semi_finished_ingredients', sa.Column('is_semi_finished', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semi_finished_ingredients', 'is_semi_finished')
    # ### end Alembic commands ###
