"""change unittype of purchase unit to inventory_batch

Revision ID: 620d847207e8
Revises: 0a2e01a41d72
Create Date: 2026-02-01 15:48:07.211793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '620d847207e8'
down_revision: Union[str, Sequence[str], None] = '0a2e01a41d72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'purchase_unit',
               existing_type=postgresql.ENUM('kg', 'gm', 'mg', 'liter', 'ml', name='unittype'),
               nullable=False)
    op.add_column('inventory_batches', sa.Column('unit', sa.Enum('kg', 'gm', 'mg', 'liter', 'ml', name='unittype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_batches', 'unit')
    op.alter_column('inventory', 'purchase_unit',
               existing_type=postgresql.ENUM('kg', 'gm', 'mg', 'liter', 'ml', name='unittype'),
               nullable=True)
    # ### end Alembic commands ###
