"""total_cost added to inventoryBatch table

Revision ID: 62c982160665
Revises: bc54b068f478
Create Date: 2026-03-27 17:43:52.592685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c982160665'
down_revision: Union[str, Sequence[str], None] = 'bc54b068f478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_batches', sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_batches', 'total_cost')
    # ### end Alembic commands ###
