"""added status field to dish preparation logs table

Revision ID: 6482195aa512
Revises: 2c5ea60fb348
Create Date: 2026-01-26 05:30:35.909404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6482195aa512'
down_revision: Union[str, Sequence[str], None] = '2c5ea60fb348'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_preparation_batch_logs', sa.Column('track_status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='preparationbatchstatus'), nullable=True))
    op.add_column('dish_preparation_batch_logs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('dish_preparation_batch_logs', sa.Column('failure_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish_preparation_batch_logs', 'failure_reason')
    op.drop_column('dish_preparation_batch_logs', 'completed_at')
    op.drop_column('dish_preparation_batch_logs', 'track_status')
    # ### end Alembic commands ###
