"""added few table for preprepared material

Revision ID: 70d33c9b55be
Revises: 7e2f0c2d1878
Create Date: 2026-01-25 05:21:36.898908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70d33c9b55be'
down_revision: Union[str, Sequence[str], None] = '7e2f0c2d1878'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_prepared_dish_preparation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('storage_location_id', sa.Integer(), nullable=True),
    sa.Column('product_type', sa.Enum('BATTER', 'SAUCE', 'PASTE', 'STOCK', 'SPICES', 'DOUGH', 'FILLING', 'GRAVY', 'OTHER', name='prepreparedproducttype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('shelf_life_hours', sa.Integer(), nullable=True),
    sa.Column('preparation_time_minutes', sa.Integer(), nullable=True),
    sa.Column('yield_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_prepared_dish_preparation_name'), 'pre_prepared_dish_preparation', ['name'], unique=False)
    op.create_index(op.f('ix_pre_prepared_dish_preparation_tenant_id'), 'pre_prepared_dish_preparation', ['tenant_id'], unique=False)
    op.create_table('pre_prepared_material_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('quantity_produced', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('quantity_remaining', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('production_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preparation_log_id', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['pre_prepared_dish_preparation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_prepared_material_stock_batch_number'), 'pre_prepared_material_stock', ['batch_number'], unique=False)
    op.create_index(op.f('ix_pre_prepared_material_stock_id'), 'pre_prepared_material_stock', ['id'], unique=False)
    op.create_index(op.f('ix_pre_prepared_material_stock_tenant_id'), 'pre_prepared_material_stock', ['tenant_id'], unique=False)
    op.create_table('ingredients_for_pre_prepared_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semi_finished_product_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('inventory_transaction_id', sa.UUID(), nullable=True),
    sa.Column('quantity_required', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('ingredient_name', sa.String(length=255), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['inventory_transaction_id'], ['inventory_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semi_finished_product_id'], ['pre_prepared_dish_preparation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_for_pre_prepared_ingredients_id'), 'ingredients_for_pre_prepared_ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_ingredients_for_pre_prepared_ingredients_tenant_id'), 'ingredients_for_pre_prepared_ingredients', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_dish_preparation_tenant_id'), table_name='dish_preparation')
    op.drop_table('dish_preparation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish_preparation',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dish_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_prepared', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=False),
    sa.Column('preparation_date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('prepared_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], name=op.f('dish_preparation_dish_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prepared_by_user_id'], ['users.id'], name=op.f('dish_preparation_prepared_by_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], name=op.f('dish_preparation_tenant_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('dish_preparation_pkey'))
    )
    op.create_index(op.f('ix_dish_preparation_tenant_id'), 'dish_preparation', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_ingredients_for_pre_prepared_ingredients_tenant_id'), table_name='ingredients_for_pre_prepared_ingredients')
    op.drop_index(op.f('ix_ingredients_for_pre_prepared_ingredients_id'), table_name='ingredients_for_pre_prepared_ingredients')
    op.drop_table('ingredients_for_pre_prepared_ingredients')
    op.drop_index(op.f('ix_pre_prepared_material_stock_tenant_id'), table_name='pre_prepared_material_stock')
    op.drop_index(op.f('ix_pre_prepared_material_stock_id'), table_name='pre_prepared_material_stock')
    op.drop_index(op.f('ix_pre_prepared_material_stock_batch_number'), table_name='pre_prepared_material_stock')
    op.drop_table('pre_prepared_material_stock')
    op.drop_index(op.f('ix_pre_prepared_dish_preparation_tenant_id'), table_name='pre_prepared_dish_preparation')
    op.drop_index(op.f('ix_pre_prepared_dish_preparation_name'), table_name='pre_prepared_dish_preparation')
    op.drop_table('pre_prepared_dish_preparation')
    # ### end Alembic commands ###
