"""reconciliation module added

Revision ID: 79e2bf6efcd7
Revises: bd9eecdd3a6a
Create Date: 2026-03-01 12:29:52.522883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e2bf6efcd7'
down_revision: Union[str, Sequence[str], None] = 'bd9eecdd3a6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
