"""add new column to inventory

Revision ID: 79f827e12533
Revises: c8c67843a87f
Create Date: 2026-01-09 00:14:32.534792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f827e12533'
down_revision: Union[str, Sequence[str], None] = 'c8c67843a87f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_ingredients', sa.Column('inventory_transaction_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'dish_ingredients', 'inventory_transactions', ['inventory_transaction_id'], ['id'], ondelete='CASCADE')
    op.add_column('inventory', sa.Column('sku', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'inventory', ['sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory', type_='unique')
    op.drop_column('inventory', 'sku')
    op.drop_constraint(None, 'dish_ingredients', type_='foreignkey')
    op.drop_column('dish_ingredients', 'inventory_transaction_id')
    # ### end Alembic commands ###
