"""add few tables for dish preparation

Revision ID: 7e2f0c2d1878
Revises: 0fac170d81de
Create Date: 2026-01-24 15:24:59.637584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e2f0c2d1878'
down_revision: Union[str, Sequence[str], None] = '0fac170d81de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish_preparation_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='preparationbatchstatus'), nullable=True),
    sa.Column('total_dishes_planned', sa.Integer(), nullable=True),
    sa.Column('total_dishes_completed', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_preparation_batches_batch_number'), 'dish_preparation_batches', ['batch_number'], unique=True)
    op.create_index(op.f('ix_dish_preparation_batches_id'), 'dish_preparation_batches', ['id'], unique=False)
    op.create_index(op.f('ix_dish_preparation_batches_started_at'), 'dish_preparation_batches', ['started_at'], unique=False)
    op.create_index(op.f('ix_dish_preparation_batches_tenant_id'), 'dish_preparation_batches', ['tenant_id'], unique=False)
    op.create_table('dish_preparation_batch_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('quantity_prepared', sa.Integer(), nullable=False),
    sa.Column('preparation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('inventory_deducted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['dish_preparation_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_preparation_batch_logs_batch_id'), 'dish_preparation_batch_logs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_dish_preparation_batch_logs_id'), 'dish_preparation_batch_logs', ['id'], unique=False)
    op.create_index(op.f('ix_dish_preparation_batch_logs_preparation_date'), 'dish_preparation_batch_logs', ['preparation_date'], unique=False)
    op.create_index(op.f('ix_dish_preparation_batch_logs_tenant_id'), 'dish_preparation_batch_logs', ['tenant_id'], unique=False)
    op.create_table('preparation_ingredient_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preparation_log_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_name', sa.String(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('quantity_consumed', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('cost_per_unit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['preparation_log_id'], ['dish_preparation_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preparation_ingredient_history_id'), 'preparation_ingredient_history', ['id'], unique=False)
    op.create_index(op.f('ix_preparation_ingredient_history_tenant_id'), 'preparation_ingredient_history', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_preparation_ingredient_history_tenant_id'), table_name='preparation_ingredient_history')
    op.drop_index(op.f('ix_preparation_ingredient_history_id'), table_name='preparation_ingredient_history')
    op.drop_table('preparation_ingredient_history')
    op.drop_index(op.f('ix_dish_preparation_batch_logs_tenant_id'), table_name='dish_preparation_batch_logs')
    op.drop_index(op.f('ix_dish_preparation_batch_logs_preparation_date'), table_name='dish_preparation_batch_logs')
    op.drop_index(op.f('ix_dish_preparation_batch_logs_id'), table_name='dish_preparation_batch_logs')
    op.drop_index(op.f('ix_dish_preparation_batch_logs_batch_id'), table_name='dish_preparation_batch_logs')
    op.drop_table('dish_preparation_batch_logs')
    op.drop_index(op.f('ix_dish_preparation_batches_tenant_id'), table_name='dish_preparation_batches')
    op.drop_index(op.f('ix_dish_preparation_batches_started_at'), table_name='dish_preparation_batches')
    op.drop_index(op.f('ix_dish_preparation_batches_id'), table_name='dish_preparation_batches')
    op.drop_index(op.f('ix_dish_preparation_batches_batch_number'), table_name='dish_preparation_batches')
    op.drop_table('dish_preparation_batches')
    # ### end Alembic commands ###
