"""category_type added in inventory

Revision ID: 80f93d7549b9
Revises: 26bf20093292
Create Date: 2026-04-03 13:16:57.940696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80f93d7549b9'
down_revision: Union[str, Sequence[str], None] = '26bf20093292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('category_type', sa.Enum('perishable', 'non_perishable', name='item_category_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'category_type')
    # ### end Alembic commands ###
