"""remove field

Revision ID: 838dae52695d
Revises: b1c52d20d99b
Create Date: 2026-01-25 12:07:35.308714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '838dae52695d'
down_revision: Union[str, Sequence[str], None] = 'b1c52d20d99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('preparation_ingredient_history_preparation_log_id_fkey'), 'preparation_ingredient_history', type_='foreignkey')
    op.create_foreign_key(None, 'preparation_ingredient_history', 'dish_preparation_batch_logs', ['preparation_log_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'preparation_ingredient_history', type_='foreignkey')
    op.create_foreign_key(op.f('preparation_ingredient_history_preparation_log_id_fkey'), 'preparation_ingredient_history', 'dish_preparation_batches', ['preparation_log_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
