"""change nullable field

Revision ID: 86cdd20c50a1
Revises: b977576f8d22
Create Date: 2026-02-04 05:27:27.087483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86cdd20c50a1'
down_revision: Union[str, Sequence[str], None] = 'b977576f8d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory', 'storage_location_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'purchase_unit_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inventory', 'reorder_point',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.alter_column('inventory_batches', 'unit',
               existing_type=postgresql.ENUM('kg', 'gm', 'mg', 'liter', 'ml', name='unittype'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_batches', 'unit',
               existing_type=postgresql.ENUM('kg', 'gm', 'mg', 'liter', 'ml', name='unittype'),
               server_default=sa.text("'kg'::unittype"),
               existing_nullable=False)
    op.alter_column('inventory', 'reorder_point',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.alter_column('inventory', 'purchase_unit_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inventory', 'storage_location_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
