"""add new column to inventory

Revision ID: 8928c8dca07d
Revises: 96f0971e1685
Create Date: 2026-01-09 10:42:02.213407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8928c8dca07d'
down_revision: Union[str, Sequence[str], None] = '96f0971e1685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('current_quantity', sa.Numeric(precision=12, scale=3), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory', 'current_quantity')
    # ### end Alembic commands ###
