"""added fields in wastage model

Revision ID: 89e02c21b73f
Revises: 999e5c7a237e
Create Date: 2026-05-06 16:43:43.156064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e02c21b73f'
down_revision: Union[str, Sequence[str], None] = '999e5c7a237e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wastage_management', sa.Column('semi_finished_qty', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('wastage_management', sa.Column('semi_finished_unit_used', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wastage_management', 'semi_finished_unit_used')
    op.drop_column('wastage_management', 'semi_finished_qty')
    # ### end Alembic commands ###
