"""fix unit_cost calculation

Revision ID: 944a1694eaaf
Revises: 80f93d7549b9
Create Date: 2026-04-05 14:43:24.579778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '944a1694eaaf'
down_revision: Union[str, Sequence[str], None] = '80f93d7549b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_batches', 'unit_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=20, scale=10),
               existing_nullable=True)
    op.alter_column('inventory_transactions', 'unit_cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=20, scale=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventory_transactions', 'unit_cost',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('inventory_batches', 'unit_cost',
               existing_type=sa.Numeric(precision=20, scale=10),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
