"""add new column to inventory again

Revision ID: 96f0971e1685
Revises: 79f827e12533
Create Date: 2026-01-09 09:25:38.137357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f0971e1685'
down_revision: Union[str, Sequence[str], None] = '79f827e12533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory', sa.Column('reorder_point', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('inventory', sa.Column('reorder_quantity', sa.Numeric(precision=12, scale=3), nullable=True))
    op.add_column('inventory', sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('inventory', sa.Column('expiry_alert_threshold_days', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('fresh_threshold_days', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('near_expiry_threshold_days', sa.Integer(), nullable=True))
    op.add_column('storage_locations', sa.Column('special_handling_instructions', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storage_locations', 'special_handling_instructions')
    op.drop_column('inventory', 'near_expiry_threshold_days')
    op.drop_column('inventory', 'fresh_threshold_days')
    op.drop_column('inventory', 'expiry_alert_threshold_days')
    op.drop_column('inventory', 'unit_cost')
    op.drop_column('inventory', 'reorder_quantity')
    op.drop_column('inventory', 'reorder_point')
    # ### end Alembic commands ###
