"""add more models

Revision ID: 9a5dfa7edc00
Revises: fbd3f53d3c64
Create Date: 2026-01-08 15:48:43.220740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5dfa7edc00'
down_revision: Union[str, Sequence[str], None] = 'fbd3f53d3c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dish_preparation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('quantity_prepared', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('preparation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('prepared_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prepared_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_preparation_tenant_id'), 'dish_preparation', ['tenant_id'], unique=False)
    op.create_table('dish_sales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('order_source', sa.Enum('DINE_IN', 'TAKEAWAY', 'ZOMATO', 'SWIGGY', 'UBER_EATS', 'OTHER_DELIVERY', name='ordersource'), nullable=False),
    sa.Column('order_reference', sa.String(length=100), nullable=True),
    sa.Column('sale_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dish_sales_tenant_id'), 'dish_sales', ['tenant_id'], unique=False)
    op.create_table('inventory_alert',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.Enum('LOW_STOCK', 'OUT_OF_STOCK', 'EXPIRY_WARNING', name='alerttype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'RESOLVED', 'SNOOZED', name='alertstatus'), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('current_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('suggested_action', sa.Text(), nullable=True),
    sa.Column('affected_dishes', sa.Text(), nullable=True),
    sa.Column('alert_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('acknowledged_by_user_id', sa.Integer(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_alert_tenant_id'), 'inventory_alert', ['tenant_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('PURCHASE', 'PREPARATION', 'SALE', 'ADJUSTMENT', 'WASTAGE', name='transactiontype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_tenant_id'), 'inventory_transactions', ['tenant_id'], unique=False)
    op.create_table('wastage_management',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wastage_type', sa.Enum('DISH', 'INVENTORY', name='wastagetype'), nullable=True),
    sa.Column('dish_id', sa.Integer(), nullable=True),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('inventory_batch_id', sa.Integer(), nullable=True),
    sa.Column('quantity_wasted', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cost_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('wastage_reason', sa.Enum('EXPIRY', 'DAMAGE', 'CONTAMINATION', 'UNSOLD_DISH', 'PREPARATION_ERROR', 'SPILLAGE', 'STAFF_MEAL', 'SAMPLING', 'OTHER', name='wastagereason'), nullable=False),
    sa.Column('wastage_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('recorded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inventory_batch_id'], ['inventory_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wastage_management_tenant_id'), 'wastage_management', ['tenant_id'], unique=False)
    op.add_column('dish_ingredients', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('dish_ingredients', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('dish_ingredients_dish_id_fkey'), 'dish_ingredients', type_='foreignkey')
    op.create_foreign_key(None, 'dish_ingredients', 'dishes', ['dish_id'], ['id'], ondelete='CASCADE')
    op.add_column('dishes', sa.Column('standard_portion_size', sa.String(length=50), nullable=True))
    op.add_column('dishes', sa.Column('yield_quantity', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('dishes', sa.Column('preparation_time_minutes', sa.Integer(), nullable=True))
    op.add_column('dishes', sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('dishes', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('dishes', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('dishes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'updated_at')
    op.drop_column('dishes', 'created_at')
    op.drop_column('dishes', 'is_active')
    op.drop_column('dishes', 'selling_price')
    op.drop_column('dishes', 'preparation_time_minutes')
    op.drop_column('dishes', 'yield_quantity')
    op.drop_column('dishes', 'standard_portion_size')
    op.drop_constraint(None, 'dish_ingredients', type_='foreignkey')
    op.create_foreign_key(op.f('dish_ingredients_dish_id_fkey'), 'dish_ingredients', 'dishes', ['dish_id'], ['id'])
    op.drop_column('dish_ingredients', 'updated_at')
    op.drop_column('dish_ingredients', 'created_at')
    op.drop_index(op.f('ix_wastage_management_tenant_id'), table_name='wastage_management')
    op.drop_table('wastage_management')
    op.drop_index(op.f('ix_inventory_transactions_tenant_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_inventory_alert_tenant_id'), table_name='inventory_alert')
    op.drop_table('inventory_alert')
    op.drop_index(op.f('ix_dish_sales_tenant_id'), table_name='dish_sales')
    op.drop_table('dish_sales')
    op.drop_index(op.f('ix_dish_preparation_tenant_id'), table_name='dish_preparation')
    op.drop_table('dish_preparation')
    # ### end Alembic commands ###
