"""add boolean true

Revision ID: aeba1357c4c9
Revises: d5086c8023aa
Create Date: 2026-01-26 12:32:38.131667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeba1357c4c9'
down_revision: Union[str, Sequence[str], None] = 'd5086c8023aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('preparation_ingredient_history', 'ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('preparation_ingredient_history', 'ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
