"""add foreign key in dish ingredient table

Revision ID: b1c52d20d99b
Revises: 70d33c9b55be
Create Date: 2026-01-25 05:26:30.862398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c52d20d99b'
down_revision: Union[str, Sequence[str], None] = '70d33c9b55be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_ingredients', sa.Column('preprepred_material_id', sa.UUID(), nullable=True))
    op.add_column('dish_ingredients', sa.Column('is_semi_finished', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'dish_ingredients', 'pre_prepared_dish_preparation', ['preprepred_material_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dish_ingredients', type_='foreignkey')
    op.drop_column('dish_ingredients', 'is_semi_finished')
    op.drop_column('dish_ingredients', 'preprepred_material_id')
    # ### end Alembic commands ###
