"""added date added to batch date

Revision ID: b8e5399e268e
Revises: 6796e25adc91
Create Date: 2026-03-27 08:49:13.340400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e5399e268e'
down_revision: Union[str, Sequence[str], None] = '6796e25adc91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_batches', sa.Column('date_added', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_batches', 'date_added')
    # ### end Alembic commands ###
