"""added fixed cost amount in semifinishedingredient table

Revision ID: b9131175e5f0
Revises: 485692ea86a7
Create Date: 2026-04-21 06:53:26.668677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9131175e5f0'
down_revision: Union[str, Sequence[str], None] = '485692ea86a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('semi_finished_ingredients', sa.Column('fixed_cost_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semi_finished_ingredients', 'fixed_cost_amount')
    # ### end Alembic commands ###
