"""add semifinised product table

Revision ID: bc54b068f478
Revises: b8e5399e268e
Create Date: 2026-03-27 15:37:11.071557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc54b068f478'
down_revision: Union[str, Sequence[str], None] = 'b8e5399e268e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semi_finished_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('yield_quantity', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semi_finished_products_id'), 'semi_finished_products', ['id'], unique=False)
    op.create_index(op.f('ix_semi_finished_products_name'), 'semi_finished_products', ['name'], unique=False)
    op.create_index(op.f('ix_semi_finished_products_tenant_id'), 'semi_finished_products', ['tenant_id'], unique=False)
    op.create_table('semi_finished_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semi_finished_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('ingredient_name', sa.String(), nullable=True),
    sa.Column('quantity_required', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('cost_per_unit', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['semi_finished_id'], ['semi_finished_products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semi_finished_ingredients_id'), 'semi_finished_ingredients', ['id'], unique=False)
    op.create_index(op.f('ix_semi_finished_ingredients_ingredient_name'), 'semi_finished_ingredients', ['ingredient_name'], unique=False)
    op.create_index(op.f('ix_semi_finished_ingredients_tenant_id'), 'semi_finished_ingredients', ['tenant_id'], unique=False)
    op.add_column('dish_ingredients', sa.Column('semi_finished_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dish_ingredients', 'semi_finished_products', ['semi_finished_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dish_ingredients', type_='foreignkey')
    op.drop_column('dish_ingredients', 'semi_finished_id')
    op.drop_index(op.f('ix_semi_finished_ingredients_tenant_id'), table_name='semi_finished_ingredients')
    op.drop_index(op.f('ix_semi_finished_ingredients_ingredient_name'), table_name='semi_finished_ingredients')
    op.drop_index(op.f('ix_semi_finished_ingredients_id'), table_name='semi_finished_ingredients')
    op.drop_table('semi_finished_ingredients')
    op.drop_index(op.f('ix_semi_finished_products_tenant_id'), table_name='semi_finished_products')
    op.drop_index(op.f('ix_semi_finished_products_name'), table_name='semi_finished_products')
    op.drop_index(op.f('ix_semi_finished_products_id'), table_name='semi_finished_products')
    op.drop_table('semi_finished_products')
    # ### end Alembic commands ###
