"""add combo_id field in wastage table

Revision ID: c574482eacf9
Revises: 944768c381cb
Create Date: 2026-05-25 09:16:21.023219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c574482eacf9'
down_revision: Union[str, Sequence[str], None] = '944768c381cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wastage_management', sa.Column('combo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wastage_management', 'combos', ['combo_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wastage_management', type_='foreignkey')
    op.drop_column('wastage_management', 'combo_id')
    # ### end Alembic commands ###
