"""add all nullable True

Revision ID: c7e20e276fb2
Revises: 86cdd20c50a1
Create Date: 2026-02-04 08:00:14.974755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7e20e276fb2'
down_revision: Union[str, Sequence[str], None] = '86cdd20c50a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dish_preparation_batch_logs', 'dish_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dish_preparation_batch_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dish_preparation_batch_logs', 'quantity_prepared',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dish_preparation_batches', 'batch_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('dish_preparation_batches', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dish_sales', 'dish_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('dish_sales', 'quantity_sold',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True)
    op.alter_column('dish_sales', 'order_source',
               existing_type=postgresql.ENUM('DINE_IN', 'TAKEAWAY', 'ZOMATO', 'SWIGGY', 'UBER_EATS', 'OTHER_DELIVERY', name='ordersource'),
               nullable=True)
    op.alter_column('ingredients_for_pre_prepared_ingredients', 'semi_finished_product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ingredients_for_pre_prepared_ingredients', 'ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ingredients_for_pre_prepared_ingredients', 'quantity_required',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.alter_column('ingredients_for_pre_prepared_ingredients', 'ingredient_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('pre_prepared_dish_preparation', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('pre_prepared_dish_preparation', 'product_type',
               existing_type=postgresql.ENUM('BATTER', 'SAUCE', 'PASTE', 'STOCK', 'SPICES', 'DOUGH', 'FILLING', 'GRAVY', 'OTHER', name='prepreparedproducttype'),
               nullable=True)
    op.alter_column('pre_prepared_material_stock', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('pre_prepared_material_stock', 'batch_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('pre_prepared_material_stock', 'quantity_produced',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.alter_column('pre_prepared_material_stock', 'quantity_remaining',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.alter_column('pre_prepared_material_stock', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('preparation_ingredient_history', 'preparation_log_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('preparation_ingredient_history', 'ingredient_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('preparation_ingredient_history', 'quantity_consumed',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.alter_column('preparation_ingredient_history', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('wastage_management', 'quantity_wasted',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=True)
    op.alter_column('wastage_management', 'unit_cost',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=True)
    op.alter_column('wastage_management', 'cost_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('wastage_management', 'wastage_reason',
               existing_type=postgresql.ENUM('EXPIRY', 'DAMAGE', 'CONTAMINATION', 'UNSOLD_DISH', 'PREPARATION_ERROR', 'SPILLAGE', 'STAFF_MEAL', 'SAMPLING', 'OTHER', name='wastagereason'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wastage_management', 'wastage_reason',
               existing_type=postgresql.ENUM('EXPIRY', 'DAMAGE', 'CONTAMINATION', 'UNSOLD_DISH', 'PREPARATION_ERROR', 'SPILLAGE', 'STAFF_MEAL', 'SAMPLING', 'OTHER', name='wastagereason'),
               nullable=False)
    op.alter_column('wastage_management', 'cost_value',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('wastage_management', 'unit_cost',
               existing_type=sa.NUMERIC(precision=12, scale=4),
               nullable=False)
    op.alter_column('wastage_management', 'quantity_wasted',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.alter_column('preparation_ingredient_history', 'unit',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('preparation_ingredient_history', 'quantity_consumed',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.alter_column('preparation_ingredient_history', 'ingredient_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('preparation_ingredient_history', 'preparation_log_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pre_prepared_material_stock', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pre_prepared_material_stock', 'quantity_remaining',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.alter_column('pre_prepared_material_stock', 'quantity_produced',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.alter_column('pre_prepared_material_stock', 'batch_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('pre_prepared_material_stock', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('pre_prepared_dish_preparation', 'product_type',
               existing_type=postgresql.ENUM('BATTER', 'SAUCE', 'PASTE', 'STOCK', 'SPICES', 'DOUGH', 'FILLING', 'GRAVY', 'OTHER', name='prepreparedproducttype'),
               nullable=False)
    op.alter_column('pre_prepared_dish_preparation', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ingredients_for_pre_prepared_ingredients', 'ingredient_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ingredients_for_pre_prepared_ingredients', 'quantity_required',
               existing_type=sa.NUMERIC(precision=12, scale=3),
               nullable=False)
    op.alter_column('ingredients_for_pre_prepared_ingredients', 'ingredient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ingredients_for_pre_prepared_ingredients', 'semi_finished_product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('dish_sales', 'order_source',
               existing_type=postgresql.ENUM('DINE_IN', 'TAKEAWAY', 'ZOMATO', 'SWIGGY', 'UBER_EATS', 'OTHER_DELIVERY', name='ordersource'),
               nullable=False)
    op.alter_column('dish_sales', 'quantity_sold',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False)
    op.alter_column('dish_sales', 'dish_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dish_preparation_batches', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dish_preparation_batches', 'batch_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('dish_preparation_batch_logs', 'quantity_prepared',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dish_preparation_batch_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('dish_preparation_batch_logs', 'dish_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
