"""added status field to dish preparation logs table

Revision ID: d5086c8023aa
Revises: 6482195aa512
Create Date: 2026-01-26 06:01:37.259123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5086c8023aa'
down_revision: Union[str, Sequence[str], None] = '6482195aa512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preparation_ingredient_history', sa.Column('preprepred_material_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'preparation_ingredient_history', 'pre_prepared_dish_preparation', ['preprepred_material_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'preparation_ingredient_history', type_='foreignkey')
    op.drop_column('preparation_ingredient_history', 'preprepred_material_id')
    # ### end Alembic commands ###
