"""rename selling price in combo table

Revision ID: d8fb1dcc7a14
Revises: f4f6a69146fa
Create Date: 2026-05-21 09:35:46.326561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8fb1dcc7a14'
down_revision: Union[str, Sequence[str], None] = 'f4f6a69146fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combos', sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('combos', 'computed_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('combos', sa.Column('computed_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('combos', 'selling_price')
    # ### end Alembic commands ###
