"""delete for_ex and forxcfd to user_branch_access

Revision ID: e024a4fb16d5
Revises: 10878ac3dd3d
Create Date: 2026-01-04 19:40:14.183923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e024a4fb16d5'
down_revision: Union[str, Sequence[str], None] = '10878ac3dd3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_branch_access', 'forxcfd')
    op.drop_column('user_branch_access', 'for_ex')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_branch_access', sa.Column('for_ex', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_branch_access', sa.Column('forxcfd', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
