"""remove unique from sku

Revision ID: e8e4d3a1ea6d
Revises: 4804545b1bcb
Create Date: 2026-04-27 06:37:51.528394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e4d3a1ea6d'
down_revision: Union[str, Sequence[str], None] = '4804545b1bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('inventory_sku_key'), 'inventory', type_='unique')
    op.create_unique_constraint('inventory_sku_tenant_key', 'inventory', ['sku', 'tenant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('inventory_sku_tenant_key', 'inventory', type_='unique')
    op.create_unique_constraint(op.f('inventory_sku_key'), 'inventory', ['sku'])
    # ### end Alembic commands ###
