"""reconciliation module added

Revision ID: f1a1e4cc091e
Revises: f726691d349f
Create Date: 2026-03-01 14:14:34.664973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1a1e4cc091e'
down_revision: Union[str, Sequence[str], None] = 'f726691d349f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('costing_method', sa.Enum('WEIGHTED_AVERAGE', 'FIFO', name='costing_method'), nullable=True),
    sa.Column('default_variance_threshold_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('require_manager_approval', sa.Boolean(), nullable=True),
    sa.Column('auto_close_on_approval', sa.Boolean(), nullable=True),
    sa.Column('approver_role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_configs_tenant_id'), 'reconciliation_configs', ['tenant_id'], unique=False)
    op.create_table('reconciliation_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('period_start_date', sa.Date(), nullable=False),
    sa.Column('period_end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_PROGRESS', 'PENDING_APPROVAL', 'APPROVED', 'CLOSED', 'REJECTED', name='reconciliation_status'), nullable=False),
    sa.Column('costing_method', sa.Enum('WEIGHTED_AVERAGE', 'FIFO', name='costing_method'), nullable=False),
    sa.Column('variance_threshold_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('submitted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('total_opening_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_purchases_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_consumption_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_wastage_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_adjustment_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_theoretical_closing_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_physical_closing_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_variance_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_periods_id'), 'reconciliation_periods', ['id'], unique=False)
    op.create_index(op.f('ix_reconciliation_periods_tenant_id'), 'reconciliation_periods', ['tenant_id'], unique=False)
    op.create_table('physical_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('counted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('count_type', sa.String(length=20), nullable=False),
    sa.Column('counted_quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('storage_location', sa.String(length=100), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('counted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['counted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['period_id'], ['reconciliation_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physical_counts_id'), 'physical_counts', ['id'], unique=False)
    op.create_index(op.f('ix_physical_counts_period_id'), 'physical_counts', ['period_id'], unique=False)
    op.create_index(op.f('ix_physical_counts_tenant_id'), 'physical_counts', ['tenant_id'], unique=False)
    op.create_table('reconciliation_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('item_sku', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('item_category', sa.String(length=100), nullable=True),
    sa.Column('opening_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('purchases_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('consumption_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('wastage_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('adjustment_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('theoretical_closing_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('physical_closing_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('variance_quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('opening_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('purchases_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('consumption_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('wastage_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('adjustment_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('theoretical_closing_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('physical_closing_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('variance_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('variance_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('variance_status', sa.Enum('WITHIN_THRESHOLD', 'EXCEEDS_THRESHOLD', 'INVESTIGATED', 'ADJUSTED', name='variance_status'), nullable=True),
    sa.Column('variance_notes', sa.Text(), nullable=True),
    sa.Column('adjustment_transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['adjustment_transaction_id'], ['inventory_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['period_id'], ['reconciliation_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_line_items_id'), 'reconciliation_line_items', ['id'], unique=False)
    op.create_index(op.f('ix_reconciliation_line_items_inventory_item_id'), 'reconciliation_line_items', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_line_items_period_id'), 'reconciliation_line_items', ['period_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_line_items_tenant_id'), 'reconciliation_line_items', ['tenant_id'], unique=False)
    op.create_table('reconciliation_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('line_item_id', sa.Integer(), nullable=True),
    sa.Column('inventory_item_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Enum('PHYSICAL_COUNT_VARIANCE', 'DAMAGE', 'THEFT', 'EXPIRY', 'DATA_ENTRY_ERROR', 'OTHER', name='adjustment_reason'), nullable=False),
    sa.Column('quantity_adjusted', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('value_adjusted', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['line_item_id'], ['reconciliation_line_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['reconciliation_periods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['inventory_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_adjustments_tenant_id'), 'reconciliation_adjustments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reconciliation_adjustments_tenant_id'), table_name='reconciliation_adjustments')
    op.drop_table('reconciliation_adjustments')
    op.drop_index(op.f('ix_reconciliation_line_items_tenant_id'), table_name='reconciliation_line_items')
    op.drop_index(op.f('ix_reconciliation_line_items_period_id'), table_name='reconciliation_line_items')
    op.drop_index(op.f('ix_reconciliation_line_items_inventory_item_id'), table_name='reconciliation_line_items')
    op.drop_index(op.f('ix_reconciliation_line_items_id'), table_name='reconciliation_line_items')
    op.drop_table('reconciliation_line_items')
    op.drop_index(op.f('ix_physical_counts_tenant_id'), table_name='physical_counts')
    op.drop_index(op.f('ix_physical_counts_period_id'), table_name='physical_counts')
    op.drop_index(op.f('ix_physical_counts_id'), table_name='physical_counts')
    op.drop_table('physical_counts')
    op.drop_index(op.f('ix_reconciliation_periods_tenant_id'), table_name='reconciliation_periods')
    op.drop_index(op.f('ix_reconciliation_periods_id'), table_name='reconciliation_periods')
    op.drop_table('reconciliation_periods')
    op.drop_index(op.f('ix_reconciliation_configs_tenant_id'), table_name='reconciliation_configs')
    op.drop_table('reconciliation_configs')
    # ### end Alembic commands ###
