"""combo reference in dish sale table

Revision ID: f4f6a69146fa
Revises: 3b060e8d7743
Create Date: 2026-05-21 07:30:08.362620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f6a69146fa'
down_revision: Union[str, Sequence[str], None] = '3b060e8d7743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_sales', sa.Column('combo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dish_sales', 'combos', ['combo_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dish_sales', type_='foreignkey')
    op.drop_column('dish_sales', 'combo_id')
    # ### end Alembic commands ###
