"""add tenant_id to rest of model

Revision ID: fbd3f53d3c64
Revises: 7e52e8c6b4f6
Create Date: 2026-01-07 15:35:35.225905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbd3f53d3c64'
down_revision: Union[str, Sequence[str], None] = '7e52e8c6b4f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_ingredients', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_dish_ingredients_tenant_id'), 'dish_ingredients', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'dish_ingredients', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='CASCADE')
    op.add_column('dish_types', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_dish_types_tenant_id'), 'dish_types', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'dish_types', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='CASCADE')
    op.add_column('dishes', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_dishes_tenant_id'), 'dishes', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'dishes', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='CASCADE')
    op.add_column('expenses', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_expenses_tenant_id'), 'expenses', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='CASCADE')
    op.add_column('inventory_log', sa.Column('tenant_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_inventory_log_tenant_id'), 'inventory_log', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'inventory_log', 'tenants', ['tenant_id'], ['tenant_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inventory_log', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_log_tenant_id'), table_name='inventory_log')
    op.drop_column('inventory_log', 'tenant_id')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_tenant_id'), table_name='expenses')
    op.drop_column('expenses', 'tenant_id')
    op.drop_constraint(None, 'dishes', type_='foreignkey')
    op.drop_index(op.f('ix_dishes_tenant_id'), table_name='dishes')
    op.drop_column('dishes', 'tenant_id')
    op.drop_constraint(None, 'dish_types', type_='foreignkey')
    op.drop_index(op.f('ix_dish_types_tenant_id'), table_name='dish_types')
    op.drop_column('dish_types', 'tenant_id')
    op.drop_constraint(None, 'dish_ingredients', type_='foreignkey')
    op.drop_index(op.f('ix_dish_ingredients_tenant_id'), table_name='dish_ingredients')
    op.drop_column('dish_ingredients', 'tenant_id')
    # ### end Alembic commands ###
